run:
  skip-files:
    - ".*_test.go"
    - "mock_.*.go"
  timeout: "100s"

linters:
  enable:
    - goimports
    - revive
    - errcheck
    - ineffassign
    - typecheck
    - unconvert
    - exportloopref
    - dupl
    - misspell
    - govet
    - staticcheck
    - unused
    - gosimple
  disable-all: true

linters-settings:
  goimports:
    local-prefixes: github.com/wasify-go
  revive:
    enableAllRules: true
    rules:
      - name: receiver-naming
        disabled: true
