#!/bin/bash

source "$(dirname "${0}")/commons.lib"

readonly PROJECT_PATH="$(realpath "$(dirname "${0}")/../..")"
readonly PROJECT_NAME="$(basename "${PROJECT_PATH}")"

function main() {
  local run_all="$(_read_cmd_flag "run-all" "true" "${@}")"
  local build_project="$(_read_cmd_flag "build" "${run_all}" "${@}")"

  if _is_truthy "${build_project}"; then
    _info "Building project '${PROJECT_NAME}'..."

    _assert_success "${PROJECT_PATH}" go mod tidy
    _assert_success "${PROJECT_PATH}" go mod vendor
    _assert_success "${PROJECT_PATH}" go build ./...
  fi
}

main "${@}"
