#!/bin/bash

source "$(dirname "${0}")/commons.lib"

readonly PROJECT_PATH="$(realpath "$(dirname "${0}")/../..")"
readonly PROJECT_NAME="$(basename "${PROJECT_PATH}")"

function main() {
  local run_all="$(_read_cmd_flag "run-all" "true" "${@}")"
  local update_dependencies="$(_read_cmd_flag "update" "${run_all}" "${@}")"

  if _is_truthy "${update_dependencies}"; then
    _info "Updating dependencies for project '${PROJECT_NAME}'..."

    _assert_success "${path}" go get -t -u ./...
  fi
}

main "${@}"
